# Generated by Django 4.1 on 2022-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_login_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
            ],
        ),
    ]
