# Generated by Django 4.1 on 2022-08-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_student_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_db',
            name='created_by',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
